### ISSUE TITLE
isPreview defaults to true

### ISSUE THREAD

**Issue by jessecascio** [micnews/apple-news#4]
Theres logic in there that overrides the default Apple News API behaviour with no documentation that this happens.  As outlined in the Apple docs on `isPreview`:

```
Default value: True if your channel has not yet been approved to publish articles in Apple News Format; False if your channel has been approved.
```

But this module explicitly sets it to `true` if not defined.

**Comment by iefserge** [comment]
@jessecascio Yep, I think this way it's more predictable and requires explicit permission to publish public articles.

**Comment by ryanscottaudio** [comment]
Added `isPreview = true` to readme.
